
# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  eventsourcerer.application_name: 'EventSourcerer'
  eventsourcerer.application_id: '%env(EVENTSOURCERER_APPLICATION_ID)%'
  eventsourcerer.host: '%env(EVENTSOURCERER_HOST)%'
  eventsourcerer.port: '%env(int:EVENTSOURCERER_PORT)%'
  eventsourcerer.url: '%env(EVENTSOURCERER_URL)%'
  eventsourcerer.secure: '%env(bool:EVENTSOURCERER_SECURE)%'
  eventsourcerer.local_certificate_directory: '%env(EVENTSOURCERER_LOCAL_CERTIFICATE_DIRECTORY)%'
  eventsourcerer.verify_peer: '%env(bool:EVENTSOURCERER_VERIFY_PEER)%'
  eventsourcerer.verify_peer_name: '%env(bool:EVENTSOURCERER_VERIFY_PEER_NAME)%'
  eventsourcerer.allow_self_signed: '%env(bool:EVENTSOURCERER_ALLOW_SELF_SIGNED)%'
  eventsourcerer.certificate_authority_file: '%env(EVENTSOURCERER_CERTIFICATE_AUTHORITY_FILE)%'
services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind:
      $eventsourcererProjectDir: '%kernel.project_dir%'

  PearTreeWeb\EventSourcerer\Client\Infrastructure\Config:
    factory: ['EventSourcerer\ClientBundle\Infrastructure\ConfigFactory', 'create']
    arguments:
      $host: '%eventsourcerer.host%'
      $url: '%eventsourcerer.url%'
      $port: '%eventsourcerer.port%'
      $applicationId: '%eventsourcerer.application_id%'
      $createSecure: '%eventsourcerer.secure%'
      $localCertificateDirectory: '%kernel.project_dir%/%eventsourcerer.local_certificate_directory%'
      $verifyPeer: '%eventsourcerer.verify_peer%'
      $verifyPeerName: '%eventsourcerer.verify_peer_name%'
      $allowSelfSigned: '%eventsourcerer.allow_self_signed%'
      $cafile: '%eventsourcerer.certificate_authority_file%'

  EventSourcerer\ClientBundle\Transport\EventSourcererTransportFactory:
    tags: [ messenger.transport_factory ]

  EventSourcerer\ClientBundle\Command\ListenForEvents:
    tags:
      - { name: console.command }

  EventSourcerer\ClientBundle\Command\GetSummary:
    tags:
      - { name: console.command }

  EventSourcerer\ClientBundle\Command\ListAllEvents:
    tags:
      - { name: console.command }

  EventSourcerer\ClientBundle\Command\Testing\ValidateWorkerSequencing:
    tags:
      - { name: console.command }

  PearTreeWeb\EventSourcerer\Client\Domain\Repository\WorkerMessages:
    class: PearTreeWeb\EventSourcerer\Client\Infrastructure\Repository\PsrCacheWorkerMessages


